spring:
    elasticsearch:
        uris: ENC[AES256_GCM,data:0sIy/u2qfGeSkTWtSzqj8CQSv74ELQbZxSuqeLBOyyZg5Q==,iv:Vs8fgG9bjF1lv8qJCsEtZYXg801jozhARm4lVj9GGA0=,tag:VmoL+fL2uzQs8kSmXW6LKw==,type:str]
        username: ENC[AES256_GCM,data:UbOn2to=,iv:4jxxE7sg8gA9TOjB4MWXstLwCNb372ICdvRfYVuk48w=,tag:jK82KjYcWhCiCqP+GrkHAQ==,type:str]
        password: ENC[AES256_GCM,data:CISIDmw=,iv:O2bOUMaJPyfkXkdr+o/zPpwwT2s522KsznWtoKeGXCk=,tag:fmh5BQTGUGL7Rszmk8N8ug==,type:str]
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:OXQgKtvT0VDXDvUQpdosqj8VnxOxmDM8By7jJVk/hgcQf+5LCPR7ACAg5NqLRL7tNdei,iv:q7jklx3ZxM7udb0hQwShIlrX2oyTTFEs81Cjl6ZE8HI=,tag:j9pD1CYZSa3ijJkl6km/Tg==,type:str]
        username: ENC[AES256_GCM,data:o0gatZd0,iv:lrVF0+kowLSGmu/656rouDGbu5l0QJu4NyJ7trYqK68=,tag:DGe+rKqRMuO/7B7Kol5UYA==,type:str]
        password: ENC[AES256_GCM,data:DNscriVgDIRtLSk=,iv:MJIYHMovzZL4rpenaBjc+vwlIEhJmSNvFac3JilcDoE=,tag:M02I2m233txhe9HWmKseYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-04T11:55:33Z"
    mac: ENC[AES256_GCM,data:r2I2Z6u7IRvFMtrtyDBzKutI82YiWl26I4W+pIl3WlO4rSQqDG/BMbY5+TuTqkKYXuEdhg9XFKZBYhNzQ8jN7Y/UuCz7OAmffXyQMFGOrMHMrP1MzADfarjUplmuf2/KbFHMGTvWsVRqhnYD/KsrNonnL0idg2KmC5d3tExQqSY=,iv:42eoxDp6rooCCQnTV1GXtPg0067VIwCzwNx0s03vzzQ=,tag:VkpLv5djlNciNmSTaDWXfw==,type:str]
    pgp:
        - created_at: "2025-11-04T11:55:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAjiPLBnnVhssoIFWPPyXzBcqKmXkt/G6clbBvkZV9Sehh
            lITL3s43LBHafTovbyxYUcWdaEcz+0RavZo0kL9hk+yQYdq+UHPc5RU+wawARYDb
            YLE9izVsSogP6dm9pt06HepJDsPBw+HroawcikQXZtvg+exSSc87QZsK4XzHRenU
            3ysJXGwCdKovPWjdBp0GcnTb0LESsLIV2htSmKPEpIsqcIDqQ6ALDNZJO38QfXun
            viIKcS74KvNNRHyhYLY9MLUm1tpJe3ZM1vJIHuzT4Q8lLrBeHFg+rv1lpDwLnhaz
            /sDpQB1bt02dGKLUJXO8GFh1syvi/JSvY9vV0OGYH31156hlOUerZsWj7Ul1EZWq
            BKw6LxlPSorvAEpIYB0RRu/Fo/FgdPM9IZaBbwv0q+4vhCmyCrsYLwtMvf3vscPF
            aDj9QxBGvFhZaOrZuYOquc2EIfn0tyNoFFRuB7UuFF5rQQkrOPo+usgsyzXG6Ij8
            5wRirCFB948zNqa9nvDKfym+izZwyTfLx1yGj657bZTg8iBEE2ePqWWl/Lnr7fHi
            7I3P2BVWZs8nVUoendhj8lKIb8DLWC5+m+30j9lKVLK+mAAe3hQThuEzGK5DqDKO
            dWI8JEKXz6ZiMXjCRE3TldN2kr8e1vbacDUYjmKBpYmf8wqSrVpLb21GV+AalsjS
            XAEcPMKO0iZXqOnk3j+q3xnnG8XLDPiI0n/GNJGzsASpQWMRUPm3tQT0Gcoj819D
            fH7J+Im0DBBXy/NM8d/0P9cAzlKXu/1tXhs2VW3ML6yekJfvaUvQ0uYSJWwH
            =Kei7
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
