spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:EGdQcyACugt0WP60Z2UB5S4yQdElXu8Mpzlqlj7Ob8drL3kDMvq4,iv:OiyeTFBA29tQmbsgH09lOO89GUdbyegJ3pY8L4P10P4=,tag:Z82WUK0ifTi5FizpHHdpEw==,type:str]
        username: ENC[AES256_GCM,data:plv7QcxT,iv:FJcporln2F6iffgzzjTw9dWp5p6zAUC5P5/UpqaEkp4=,tag:oPPVS6odB1q3mQi7st9Scw==,type:str]
        password: ENC[AES256_GCM,data:J3idSKmne71yM3g=,iv:ZYxpwTKkbd8Vqpe+ndzU5Bic575oznOPs+6PqwloUsM=,tag:KMwyzvN1UUsvUvm9mAIfAg==,type:str]
opensearch:
    host: ENC[AES256_GCM,data:FLY6asVA7KgAPbT50V9dAy6cgiIp35i51VDrYKiRhP3k,iv:8issvue/lKAlnZnFf5113p1/MZDXfXfCJsfNrK+Lm20=,tag:Rt0IQrYnVyDdALg0T6kQAA==,type:str]
    port: 9200
    username: ENC[AES256_GCM,data:eXyNOJg=,iv:+Kl/Yug0nV3FFWFJJ0Mp1ujGeUa7SXWubiw4hw3nyMg=,tag:7bvq//zf2Txg5fPLXIOtHw==,type:str]
    password: ENC[AES256_GCM,data:CrcFKUlKYqdxw2o=,iv:WB03yGJoqRq+YNveRJ0nLyFuPFpXeyqMD3hf0AvFufk=,tag:T9xbD7lwwOhqKQf5QgYeqQ==,type:str]
    truststore:
        path: /certs/truststore.jks
        password: ENC[AES256_GCM,data:wWhb52pCuIf+03Iv9dXfQjYUj7rFnA==,iv:HHP8Irk0jlKZ+b/8BdLxV0uQVDFaGBpLjn05EdxZoBY=,tag:2M37g5r+0M/x8GFuZLwX1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-14T05:26:21Z"
    mac: ENC[AES256_GCM,data:TQxBPJwTRDkzcqt/dqg50DkJnR7w1XjiVyfkdIXmDB56R/0zv3I0uolUsjPTtIRr53GIrMz+8JrTo+ndhBbw2BGRZa0X+iyxEvPJ8PAzPJX+I9Pdd3qEbg4Tx8+mnIpGXAIgswBp2NbTK9RT/E+Y/RzMQDBiOEmCaUGB38B45Vg=,iv:LONSoDvlV4SqnrRCEL3kp7OryWg/tVTZJDDAJbEHMM8=,tag:tz41bcdAb+Olxoix4tnn1w==,type:str]
    pgp:
        - created_at: "2025-12-14T05:26:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAw7CIqp7LON1DXB7GHnxtvNIahhUAGva0clD6irECHNkg
            d5YN9bSVfbQLlktidkT2lpjpcUn1LtQ3cmbWtPBG6IsH58O36D+CRvwtWDqW9wwN
            P94dxslijKLC/KnCVeFUIOrKh8x/7ezPjKg9g53Qgrof2+JiB04OztlwGxLPoO1d
            P+agfCWym6YVGXecvy6u3Nfdk7DNV2Y7Qn8rR32fNhZGpBQRJaZblIlP4JmpNlYY
            I19u7GV6wosyDwVst/bAIOlbf0g5/lEuv1CdsgQiDriYjv6foR6fXCtCvhHOe9ZH
            YKQFV49Ngx1W8r96s1qXcuBQRWEkGxrGosAG5o/5EhXSMvtvJG5RMwx8XL7DtaQg
            5komIPujZukLgVfPZkJYtkdMZ2ihry112cmJOS0asbQQCQrUn1zCNiSoGE42lC/U
            g54+G24KXjxhbXMiAdkMQ1h5qrlrAmEk9pnuWfCIpAiTQPzQ62UfJJi3vKp+A8Vu
            E2igiLHYvJm1jFC4YsBAhiiQBan3s6rvbJJYVjEDhy3URqWkXpDh38OGdhj5nMtF
            WY6vOtKYup8mN1tQnyK+/ZrNCUVT4cN92O/jM8Wi+g5V7aymS0mpa5qGb3oIQXR6
            inOYE9eeY7E+Qi/o7X9TiQj6a1EGahb58+h7A4I4ksVjUzhfuBuhVlfX3QimXSrS
            XAGd/bAVMRgXTioJTEutXwJbKELNvBf5EBVA45tqqll7r/1xXtP5rh7WYSDQFcmf
            0xIK5UXlgEsLVM47oZ9i0BrkdMFjwyHRsV9ingzsGclglkoiRER3OEGnOjbF
            =PPiy
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
