spring:
    application:
        name: replay-batch
    profiles:
        active: local
    jpa:
        properties:
            hibernate:
                jdbc:
                    fetch_size: 1000
        open-in-view: false
        hibernate:
            ddl-auto: none
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-14T05:26:21Z"
    mac: ENC[AES256_GCM,data:jyP3a6xQgAlGS5BQjTUMb7AAmT33pXfRYd/vU7jlFMz0bCWU24gBFntCMIoHorpUa0mF8QIB/WWI1Fs6KgyE8dmnkqWp25PNxzqZUfIv74OAkCdRitLUNGOTdVdLScHoAlID+deGXP8yIMx+/za/W+wUAFAj+7Rw+ifu+vlk27g=,iv:MDH72D6oghN8ABI89geBcLIcFcPXNvcjNNO82THhiHk=,tag:2idjezO2pb6On/dM+aH1Rw==,type:str]
    pgp:
        - created_at: "2025-12-14T05:26:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//RxtQSDgNaBhBOdUIygcQzdkIa6O9P7A+V9Juhkv+dqZg
            gxSem7lQ0lV7dXdplriV42/LmQUkLdq/0h0kPLkukAJC2HvnznCdTznjSqLb8Ejh
            3b9odLvbp3clg957EPyu7KMLNGyZ+T7EAs9FThOJ5/ttPh9eFoBWNA70JpW3901U
            D1t9KD8gsn9EI+Ej3bM0f9rqc0hjFu5CW5KqwhDw2KfExjWSoGWFjZ4GgKIlxGGQ
            hk+uvAW0HlbZDUCVBB1Zga/dZgJfhRzOjHVVujfTQGJjEbP40YYFeu1ZDtO3kX3B
            cIYElqdTeIBZ/jCc26t2xadGQSZQKtLdLZTlXbNN7xJ/UcZtpPwuE39nheNgGojo
            d9fwWr47YNx5yNGFIJhTDaDu9ZngCjldiYgHGzK5um80CVt+shm0fdPXwU+Sk12J
            6EA5tgUkRFh1hhp8qw4qJyn03uDSbLNLCad94+ZCg4xtNdyGXPYHkvg+uqAf+jo+
            Xdhpe6zC1LsJogS1Ezkr6FI2x73fLrpeHGTNSYcyWKAb4lNvUR2//eFd+UivTYQv
            f9mUKH4+pEuV8/lJlS6QdBRp6aMjDro1Q9SPCipfaA7nUVAKhnTMwN8e2+QLv07a
            n8ZXSdmyOtWvBcb4qoJuRw1BRxUewzSFt4v3MOqdM49ldjnsyH5yeePjW98dKNvS
            XgEM9MCO0OZqw6VyD9l4fmzsklHFKJls+kz8GWdIjZeccpviex1TAbugINFy6Kfz
            91fX95m61OWUwVRyQCMG9+TEJCdj3OnpYiESufWKHnqarjtUrcb5sRqbdwGSjnM=
            =JDtj
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
